# Generated by Django 5.1.2 on 2024-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dobanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca', models.CharField(max_length=100)),
                ('dobanda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_actualizare', models.DateField(auto_now=True)),
            ],
        ),
    ]
